### PR TITLE
feat: show min/max on map legend

### LINKED ISSUE #130: [Design] Add min and max values to legend
**Issue**

Currently, the legend bar shows real values for the break points, but not the min and max values.

image

**Recommendation**

Add min max values at the end of the legend bar (continuing existing text style) to improve data clarity.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
Min + Max values are not shown explicitly on the Legend

This is helpful information since the bins may not all be the same width

Fixes #130 

## Approach
* Calculate and show min + max values on the BinLabels

## How to Test
1. Navigate to https://deploy-preview-140--chicago-env-explorer.netlify.app/map
    * You should see that the bin values now extend to the edge of the Legend (at the bottom)
2. Select a few different variables
    * You should see the min + max values do not extend off of the Legend (worst case: Population Density)

### CODE REVIEW

**Comment by bodom0015** [comment]
Per @Makosak's request, also setting `active=FALSE` for "Heat Index (Average)" :+1:

**Review by mradamcox — CHANGES_REQUESTED** [review]
Ok, I spent some time trying to see if I could get around the negative margins and 110% width to improve alignment. Had a bit of luck putting `justify-content: space-between` on the `BinLabels` div and `width:1px` on `BinLabels.bin`. However, I found that with some variables there aren't actually enough `bins` entries passed to the `Legend` component, and this is a deeper underlying issue that I think we should resolve before continuing work on this PR. See #151.

**Comment by bodom0015** [comment]
Thank you, @mradamcox! I found that there was a hardcoded `6` for all bin counts, but the Air Quality variables expected 8 bins instead

I've adjusted the reducers/generateQuantileBins function to use `colorScale` to determine number of bins, and it should fallback to the previous `6` if colorScale is unavailable :+1:

I also noticed that 2 variables (namely Vegetation Index + Adult Asthma Cancer) sometimes contain strings, so they were showing NaN as min+max.. I've adjusted the calculations to filter these `NaN` values out before determining min/max

**Comment by mradamcox** [comment]
Great! Bin numbers fixed, but I was still not liking the spacing of these labels because in a lot of cases they get to be unclear when they are offset, for example:
image
and
image

I wanted something more structurally tied to the bar divs themselves, instead of approximately underneath, so for all of the non-categorical variables (everything besides the Historical Redlining and Displacement Pressure variables) I injected offset divs within the color bars themselves, which provides a much cleaner result:

image

image

image

However, @bodom0015 I just could not figure out how to acquire the `min` and `max` values within the Legend component, the way you had done within the BinLabel component. So, could you take one more pass at this and just replace my min/max values on lines 195/196 with actual values?

Also, I commented out a bit of code but left it for your reference, so you can remove that when you make the final commit.

Hopefully this attention to the legend will be useful when we get to the new types of layers that we have in mind.

**Review by mradamcox — CHANGES_REQUESTED** [review]
see above for requested changes.

**Comment by bodom0015** [comment]
Hi, @mradamcox! I think this is a great idea, but noting that there still appears to be the issue where the `max` label can extend off of the Legend (e.g. Population Density)

Screenshot 2024-04-16 at 11 04 15 AM
Screenshot 2024-04-16 at 11 04 24 AM
Screenshot 2024-04-16 at 11 04 34 AM

**Review by mradamcox — APPROVED** [review]
Thanks @bodom0015 this is great. I think variableName is what was giving me so much trouble, so thanks for renaming that. I think the overlap at the edge is worth the improvement in alignment.

**Pull request merged**
