### PR TITLE
feat: added Displacement Pressure variable + links to data

### LINKED ISSUE #117: Swap displacement index with new source
DePaul team will add new displacement index source that shows better variability/variation across the city.

@dajoin-williams, you can add the index using the data contribution instructions here: https://docs.google.com/document/d/12lwkCAXxI9eW4Mdf6gaeR6LCsaNI3E0E6xvi7dqXr9k/edit#heading=h.l1v8ypz3kdpr 

This publishes the data as a google spreadsheet, with the join key = geoid (should be the 10-digit FIPS code)

You will also need to generate a new metadata google doc, and can use the previous one as a guide: https://docs.google.com/document/d/12LnNSq__94Aw-Twohb3ILmrGdtad6s77MO_gALS_Yzc/edit?usp=sharing

When complete, you can use this form to submit all the materials at once: https://docs.google.com/forms/d/e/1FAIpQLSdu5zCJcvLXp8eY0p3jLuCWPKSuGHjrw2auO3BsD57ssH4_wA/viewform 

When complete, please tag @Makosak and @mradamcox so we can review, and start the process of swapping displacement index.

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
New data has been provided for Displacement Pressure - we would like to integrate this into the existing ChiVes map data

Fixes #117 

## Approach
* Added new data sheet link to Sheets
* Added `VUL_PRICE`, `VULNERABLE`, and `CHANGE` to Columns
* Added `Displacement Pressure` to Variables
* Adjust `MapSection` + `Legend` to support new variables / values

### TODOs
* Verify map / data correctness
* Description for new "Displacement Pressure" variable
* Replace `0` with `Not Vulnerable`?
* Use the same color scale as the previous data? Exclude 0 from color scale? Can this color be transparent?

## How to Test
1. Navigate to https://deploy-preview-127--chicago-env-explorer.netlify.app/map
2. On the left side, expand the list of Variables
3. Scroll down and select "Displacement Pressure" from the list - this is the new variable + data
    * You should see the new variable data / scale is displayed on the map

### CODE REVIEW

**Review by mradamcox — CHANGES_REQUESTED** [review]
Looking really good. Just a couple of things to address:

1) The data description needs to be updated, likely pulled from the metadata document that has already been submitted. This description should have a description of terms like the existing Displacement Index (adding the names of corresponding colors in the description would be good too). 

2) I'm personally unsure if we are removing the existing Displacement Index in favor of this new one, or retaining it so both are available. We'll check about it.

**Comment by bodom0015** [comment]
Thank you, @mradamcox! I've updated this branch with the following :+1:

1. Pulled a basic description from the submitted Metadata document, although this could likely be improved to include color information (once we have verified the color scale)
2. Removed previous Displacement Index variable in favor of this new metric
3. Pulled from `main` to include the new industrial/non-residential overlay

**Comment by bodom0015** [comment]
@mradamcox Thank you, and sorry for missing that link!

I've updated the Metadata Link and rebuilt the data :+1: I think it should now be using the correct link, but if this is still incorrect I can give it another try :)

**Comment by mradamcox** [comment]
Looks good! Merging now. Thanks for your work on this.

**Pull request merged**
