### PR TITLE
feat: Hide inactive variables, include TXT instructions with CSV download (as ZIP)

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
1. It would be nice to show users who download the CSV from the Index Builder how the numerical data was derived
2. Some variables may need to be temporarily disabled without removing them from the Google Sheet

## Approach
1. Include customized TXT instructions (with selected indicators + weights) with CSV, download both files as ZIP to avoid browser security warnings (e.g. "This site is trying to download multiple files")
2. Added a new column to the Data Dictionary and Variables sheet: `active`
    * if `TRUE`, show this variable on the `/map` and other views in the UI
    * if `FALSE`, skip parsing this variable and disable it from affecting any of the views in the frontend application
    * Set active for all variables to `TRUE`, except for Observed PM2.5 which should be disabled

## How to Test

**ZIP Download**
"Download > CSV" now downloads a ZIP file containing the CSV alongside a TXT explanation

1. Navigate to https://deploy-preview-135--chicago-env-explorer.netlify.app/builder
2. Choose one or more Indicators (e.g. Surface Temperature + Child Asthma Rate) and click Next at the bottom-right
3. Assign weights to each indicator and click Next at the bottom-right
4. On the "Summary & Map" view, expand the Download dropdown at the bottom-left and pick CSV
    * You should see a download start for a file named `chives-custom-index.zip`
5. After the download completes, open the ZIP file
    * You should see that the zip file contains `chives-custom-index.csv` and `README.txt`
6. Open the CSV file
    * You should see all numerical data associated with computing this custom index
7. Open the TXT file
    * You should see an explanation of how this Custom Index data was computed

**Active/Inactive Variables**
Observed Particulate Matter (PM2.5) has been marked as inactive, and should not appear in the frontend at all

1. Navigate to https://deploy-preview-135--chicago-env-explorer.netlify.app/map
2. Expand the Variables dropdown
    * You should see that "Observed Particulate Matter (PM2.5)" is no longer listed under "Air Pollution"
3. Navigate to https://deploy-preview-135--chicago-env-explorer.netlify.app/builder
    * You should see that "Observed Particulate Matter (PM2.5)" is no longer listed under "Air Pollution"
4. Navigate to https://deploy-preview-135--chicago-env-explorer.netlify.app/data
    * You should see that "Observed Particulate Matter (PM2.5)" is no longer listed under "Map Variables and Data Sources"

### CODE REVIEW

**Review by mradamcox — CHANGES_REQUESTED** [review]
@bodom0015 The DEBUG variable is a good idea. Can you refactor it up to an environment variable stored in .env? Then we can even implement it elsewhere in the code if we need. (Sorry I didn't see this PR until this morning.)

**Comment by mradamcox** [comment]
Also, the explanation in the zip readme is great, we should ultimately pull that into the interface somewhere as well.

**Comment by bodom0015** [comment]
Thank you, @mradamcox! I've updated this PR to read the DEBUG variable from `.env` as `REACT_APP_DEBUG`

Truthy values: `t`, `T`, `true`, `TRUE`, etc
If value is missing or if any value does not contain `t` (case insensitive), then it is considered `false`

and I can ask Shubham if there is a good place to include the contents of the TXT file that explain how the Custom Index is built :+1:

**Review by mradamcox — APPROVED** [review]
Looks good!

**Pull request merged**
