### PR TITLE
feat: Added new variables - Air Temperature / Heat Index (Average) / Heat Index (Maximum)

### PR DESCRIPTION
**Pull request by bodom0015**
## Problem
New variables have been submitted by @jluiuc: Average Temp + Average Heat Index

These need to be added to the ChiVes map

## Approach
* Added the new variables to the ChiVes map
* Recategorized / renamed variables according to shared spreadsheet

## How to Test
1. Navigate to https://deploy-preview-129--chicago-env-explorer.netlify.app/map
2. From the Variables list, choose "Air Temperature"
    * You should see the map update with the new values + colors + Legend
3. From the Variables list, choose "Heat Index (Average)"
    * You should see the map update with the new values + colors + Legend
4. From the Variables list, choose "Heat Index (Maximum)"
    * You should see the map update with the new values + colors + Legend

### Screenshots

Screenshot 2024-03-11 at 2 31 07 PM

Screenshot 2024-03-11 at 2 31 21 PM

Screenshot 2024-03-11 at 2 31 28 PM

### CODE REVIEW

**Review by mradamcox — APPROVED** [review]
@bodom0015 Looks good to me, thanks! Only detail to add is "UIUC HeRoP Lab" as the Contributor for these two new columns (as viewed on the /data page). This is in the Google Doc so no real need to update code in this PR as far as I'm concerned. I'll ping the others before merging.

**Review by jluiuc — COMMENTED** [review]
Looks good to me!

**Comment by mradamcox** [comment]
@bodom0015 @jluiuc I'm going to convert this back to a draft until we have the newly requested max heat data.

**Comment by bodom0015** [comment]
@mradamcox @jluiuc I've added the new "Heat Index (Maximum)" variable here

Variable names + categories have also been adjusted according to the spreadsheet shared by @Makosak :+1:

Marking this as Ready for Review, if anyone has a chance to take a look :)

**Pull request merged**
